// tailwind.config.js
module.exports = {
  content: [
    "./components/**/*.{vue,js,ts}",
    "./layouts/**/*.{vue,js,ts}",
    "./pages/**/*.{vue,js,ts}",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
    // Add any custom directories where you use Tailwind classes
    "./containers/**/*.{vue,js,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgba(var(--primary-color) , 1)",
          50: "rgba(var(--primary-color) , 0.05)",
          100: "rgba(var(--primary-color) , 0.1)",
          200: "rgba(var(--primary-color) , 0.2)",
          300: "rgba(var(--primary-color) , 0.3)",
          400: "rgba(var(--primary-color) , 0.4)",
          500: "rgba(var(--primary-color) , 0.5)",
          600: "rgba(var(--primary-color) , 0.6)",
          700: "rgba(var(--primary-color) , 0.7)",
          800: "rgba(var(--primary-color) , 0.8)",
          900: "rgba(var(--primary-color) , 0.9)",
          950: "rgba(var(--primary-color) , 0.95)",
        },
        secondary: {
          DEFAULT: "rgba(var(--secondary-color) , 1)",
          50: "rgba(var(--secondary-color) , 0.05)",
          100: "rgba(var(--secondary-color) , 0.1)",
          200: "rgba(var(--secondary-color) , 0.2)",
          300: "rgba(var(--secondary-color) , 0.3)",
          400: "rgba(var(--secondary-color) , 0.4)",
          500: "rgba(var(--secondary-color) , 0.5)",
          600: "rgba(var(--secondary-color) , 0.6)",
          700: "rgba(var(--secondary-color) , 0.7)",
          800: "rgba(var(--secondary-color) , 0.8)",
          900: "rgba(var(--secondary-color) , 0.9)",
          950: "rgba(var(--secondary-color) , 0.95)",
        },
        contrast1: {
          DEFAULT: "rgba(var(--primary-contrast-color) , 1)",
          50: "rgba(var(--primary-contrast-color) , 0.05)",
          100: "rgba(var(--primary-contrast-color) , 0.1)",
          200: "rgba(var(--primary-contrast-color) , 0.2)",
          300: "rgba(var(--primary-contrast-color) , 0.3)",
          400: "rgba(var(--primary-contrast-color) , 0.4)",
          500: "rgba(var(--primary-contrast-color) , 0.5)",
          600: "rgba(var(--primary-contrast-color) , 0.6)",
          700: "rgba(var(--primary-contrast-color) , 0.7)",
          800: "rgba(var(--primary-contrast-color) , 0.8)",
          900: "rgba(var(--primary-contrast-color) , 0.9)",
          950: "rgba(var(--primary-contrast-color) , 0.95)",
        },
        contrast2: {
          DEFAULT: "rgba(var(--secondary-contrast-color) , 1)",
          50: "rgba(var(--secondary-contrast-color) , 0.05)",
          100: "rgba(var(--secondary-contrast-color) , 0.1)",
          200: "rgba(var(--secondary-contrast-color) , 0.2)",
          300: "rgba(var(--secondary-contrast-color) , 0.3)",
          400: "rgba(var(--secondary-contrast-color) , 0.4)",
          500: "rgba(var(--secondary-contrast-color) , 0.5)",
          600: "rgba(var(--secondary-contrast-color) , 0.6)",
          700: "rgba(var(--secondary-contrast-color) , 0.7)",
          800: "rgba(var(--secondary-contrast-color) , 0.8)",
          900: "rgba(var(--secondary-contrast-color) , 0.9)",
          950: "rgba(var(--secondary-contrast-color) , 0.95)",
        },
        background: {
          DEFAULT: "rgba(var(--body-bg) , 1)",
          50: "rgba(var(--body-bg) , 0.05)",
          100: "rgba(var(--body-bg) , 0.1)",
        },
        mgray: {
          DEFAULT: "rgba(var(--text-color) , 1)",
          50: "rgba(var(--text-color) , 0.05)",
          100: "rgba(var(--text-color) , 0.1)",
          200: "rgba(var(--text-color) , 0.2)",
          300: "rgba(var(--text-color) , 0.3)",
          400: "rgba(var(--text-color) , 0.4)",
          500: "rgba(var(--text-color) , 0.5)",
          600: "rgba(var(--text-color) , 0.6)",
          700: "rgba(var(--text-color) , 0.7)",
          800: "rgba(var(--text-color) , 0.8)",
          900: "rgba(var(--text-color) , 0.9)",
          950: "rgba(var(--text-color) , 0.95)",
        },
      },
      // Additional custom text color utilities
      textColor: {
        theme: {
          base: "rgba(var(--text-color) , 1)",
          muted: "rgba(var(--text-color) , 0.7)",
          light: "rgba(var(--text-color) , 0.5)",
        },
      },
      // Background color utilities
      backgroundColor: {
        theme: {
          base: "rgba(var(--body-bg) , 1)",
          surface: "rgba(var(--body-bg) , 0.8)",
          hover: "rgba(var(--primary-color) , 0.1)",
        },
      },
    },
  },
};
